apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: multi-replica-web
spec:
  type: ClusterIP
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  
  # Kubernetes Load Balancing Strategy
  # - sessionAffinity: None (default) = Random distribution
  # - sessionAffinity: ClientIP = Sticky sessions
  sessionAffinity: None
