apiVersion: v1
kind: Service
metadata:
  name: theme-app-service
  namespace: dynamic-theme-demo
spec:
  type: ClusterIP
  selector:
    app: theme-app
  ports:
  - port: 80
    targetPort: 5000
    name: http
