apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: health-check-demo
spec:
  type: ClusterIP
  selector:
    app: health-check-app
  ports:
  - port: 80
    targetPort: 5000
    name: http
