apiVersion: v1
kind: Service
metadata:
  name: env-switcher
  labels:
    app: env-switcher
spec:
  type: NodePort
  selector:
    app: env-switcher
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
    name: http
